[opcache]
; Mengaktifkan OPcache untuk Web (FPM)
opcache.enable = 1

; Matikan OPcache untuk CLI di Development
opcache.enable_cli = 0

; Alokasi Memori (Sesuai container RAM 512MB)
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 15000

; Deteksi Perubahan Kode Instan (Kunci Utama Development)
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0

; Resolusi Path & Volume Mount Docker
opcache.revalidate_path = 1

; WAJIB untuk Laravel & PHP 8+ (Attributes, Annotations, Reflection)
opcache.save_comments = 1

; Nonaktifkan JIT di Development
opcache.jit = disable
opcache.jit_buffer_size = 0