name: inventory-asset-management

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inv_asset_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - vendor_data:/var/www/html/vendor
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:ro
      - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/zz-custom-pool.conf:ro
    networks:
      - inv_asset_network
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: inv_asset_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - vendor_data:/var/www/html/vendor
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - inv_asset_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: inv_asset_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-inventory_asset_db}
      MYSQL_USER: ${DB_USERNAME:-inv_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root_secret}
    ports:
      - "${FORWARD_DB_PORT:-3307}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - inv_asset_network

  redis:
    image: redis:alpine
    container_name: inv_asset_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - inv_asset_network

  mailpit:
    image: axllent/mailpit:latest
    container_name: inv_asset_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - inv_asset_network

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
  vendor_data:
    driver: local

networks:
  inv_asset_network:
    name: inv_asset_network
    driver: bridge